mynginx:
    build: ./nginx
    ports:
        - "80:80"    
    volumes:
        - ./app:/var/www/app 
    links:
        - myfpm
        - mydb

myfpm:
    build: ./fpm
    volumes:
        - ./app:/var/www/app  

mydb:
  image: postgres
  environment:
    POSTGRES_PASSWORD: mydockerpassword
    POSTGRES_USER: mydockeruser
    POSTGRES_DB: mydockerdatabase
# myfpm:
#     image: php:7-fpm